CLASS LHC_ZGAB_RAP_R_100ATRAV1 DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZGAB_RAP_R_100ATRAV1
        RESULT result,
      earlynumbering_create FOR NUMBERING
            IMPORTING entities FOR CREATE ZGAB_RAP_R_100ATRAV1.
ENDCLASS.

CLASS LHC_ZGAB_RAP_R_100ATRAV1 IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD earlynumbering_create.
  ENDMETHOD.

ENDCLASS.
